In [33]:
import torch
import torch.nn as nn

In [34]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward (self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    

In [35]:
# Create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call for forward pass
model(features)


tensor([[0.4223],
        [0.4362],
        [0.4674],
        [0.4139],
        [0.4509],
        [0.4286],
        [0.3856],
        [0.4583],
        [0.4223],
        [0.4758]], grad_fn=<SigmoidBackward0>)

In [36]:
model.linear.weight

Parameter containing:
tensor([[ 0.4471, -0.1533, -0.4215,  0.3359, -0.3461]], requires_grad=True)

In [37]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# more complex nn

  input                ouput     

             hidden

              Bias    bias
    o
                o       
    o               

    o           o       o --------0(y_pred)

    o               
                o
    o

  5 x 3        3x1     

              Relu     sigmoid

In [38]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward (self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [39]:
# Create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call for forward pass
model(features)

tensor([[0.3584],
        [0.3789],
        [0.3714],
        [0.3463],
        [0.3720],
        [0.3683],
        [0.3590],
        [0.3527],
        [0.3625],
        [0.3756]], grad_fn=<SigmoidBackward0>)

In [40]:
model.linear1.weight


Parameter containing:
tensor([[ 0.0014,  0.0532, -0.1721, -0.1903,  0.3816],
        [-0.3940, -0.2586,  0.1632,  0.1854,  0.0332],
        [-0.4201,  0.2287,  0.3439, -0.1496,  0.4275]], requires_grad=True)

In [41]:
model.linear2.weight

Parameter containing:
tensor([[-0.4256,  0.3809, -0.1688]], requires_grad=True)

In [42]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Container

In [43]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
            )
    
    def forward (self, features):
        out = self.network(features)
        return out

In [44]:
# Create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call for forward pass
model(features)

tensor([[0.6301],
        [0.6566],
        [0.6742],
        [0.6594],
        [0.6476],
        [0.6318],
        [0.6781],
        [0.6736],
        [0.6596],
        [0.6678]], grad_fn=<SigmoidBackward0>)

In [45]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# %%
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

# %%
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

# %%
df.head()

# %% [markdown]
# # train test split

# %%
X_train, X_test, y_train, y_test = train_test_split(df.iloc[ :,1:], df.iloc[ :, :1], test_size=0.2)

# %% [markdown]
# # scaling

# %%
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# %% [markdown]
# # label encoding

# %%
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

# %%
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()


c:\Users\gis28\Downloads\Me\Pytorch\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\gis28\Downloads\Me\Pytorch\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


# Building Model

In [46]:
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        return out
    
    
    

# Important Parameter

In [47]:
learning_rate = 0.1
epochs = 30


In [48]:
loss_function = nn.BCELoss()

# Training Pipeline

In [49]:
model = Model(X_test_tensor.shape[1])

# optimizer
optimizer =  torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):

    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradient
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameter update
    # with torch.no_grad():
    #     model.network[0].weight -= learning_rate * model.network[0].weight.grad
    #     model.network[0].bias -= learning_rate * model.network[0].bias.grad
    
    # model.network[0].weight.grad.zero_()
    # model.network[0].bias.grad.zero_()

    optimizer.step()


    print(f"Epoch: {epoch+1}, loss: {loss.item()}")

Epoch: 1, loss: 0.6407272815704346
Epoch: 2, loss: 0.6241808533668518
Epoch: 3, loss: 0.6084726452827454
Epoch: 4, loss: 0.593678891658783
Epoch: 5, loss: 0.5796207189559937
Epoch: 6, loss: 0.5664355754852295
Epoch: 7, loss: 0.553754448890686
Epoch: 8, loss: 0.5415539741516113
Epoch: 9, loss: 0.5296099781990051
Epoch: 10, loss: 0.5180913805961609
Epoch: 11, loss: 0.5067504048347473
Epoch: 12, loss: 0.4954736828804016
Epoch: 13, loss: 0.4842577874660492
Epoch: 14, loss: 0.47325801849365234
Epoch: 15, loss: 0.4624289572238922
Epoch: 16, loss: 0.45173734426498413
Epoch: 17, loss: 0.4411490559577942
Epoch: 18, loss: 0.43064817786216736
Epoch: 19, loss: 0.4202645719051361
Epoch: 20, loss: 0.40989840030670166
Epoch: 21, loss: 0.39964476227760315
Epoch: 22, loss: 0.389495313167572
Epoch: 23, loss: 0.37941092252731323
Epoch: 24, loss: 0.36944788694381714
Epoch: 25, loss: 0.359656423330307
Epoch: 26, loss: 0.3499496877193451
Epoch: 27, loss: 0.3404102325439453
Epoch: 28, loss: 0.331070363521575

In [50]:
X_train_tensor.shape

torch.Size([455, 30])

In [51]:
model.network[0].weight

Parameter containing:
tensor([[ 0.2916, -0.0315,  0.1907,  0.2920, -0.0468,  0.2754,  0.2002,  0.1762,
          0.0936, -0.0915,  0.1713, -0.1439,  0.0143,  0.1507, -0.0223, -0.1143,
          0.0204, -0.0667, -0.1536, -0.1473,  0.3118,  0.0475,  0.1748, -0.0518,
          0.0996,  0.1830,  0.0748,  0.1770,  0.0754, -0.0215],
        [-0.0778,  0.1248, -0.0886,  0.1000,  0.1551,  0.1583,  0.1519,  0.1501,
          0.1723, -0.0297,  0.0029, -0.0161, -0.1166,  0.0518,  0.1089,  0.1768,
          0.0605, -0.0609, -0.1700, -0.1372,  0.0773,  0.0023,  0.2653,  0.2113,
         -0.0860, -0.0348,  0.1885,  0.1613,  0.2269,  0.1466],
        [-0.1230,  0.0624, -0.1927, -0.0685, -0.1274, -0.0389,  0.0088, -0.0938,
          0.0643,  0.0404, -0.1010,  0.0836, -0.2231,  0.0083,  0.2039, -0.1188,
          0.1053, -0.0748,  0.0310,  0.0984, -0.2403, -0.0458, -0.1022, -0.2187,
         -0.1572, -0.1538, -0.0555, -0.0317, -0.1867, -0.1225]],
       requires_grad=True)

# Evaluation

In [52]:
with torch.no_grad():
    y_pred = model(X_train_tensor)
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred==y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.610005795955658
