In [2]:
import torch

In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("no")

no


# Creating a Tensor

In [4]:
# empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
# using zeroes 
# for initializing biases with 0 in NN
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand  0-1 value which will be random
torch.rand(2,3)

tensor([[0.7331, 0.6875, 0.7810],
        [0.0230, 0.0478, 0.8681]])

In [9]:
# # manual_seed
# torch.manual(100)
# torch.rand(2,3)

In [10]:
# tensor
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [11]:
# arange
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [12]:
# linspace -> linearly space
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

# Creating Matrix

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
# torch.rand_like(x)

# tensor Data type

In [18]:
x.dtype

torch.int64

In [19]:
torch.tensor([1.0,2.2,30.4], dtype = torch.int32)

tensor([ 1,  2, 30], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [21]:
#using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical operations

# 1. Scaler Operation

In [22]:
x = torch.rand(2,2)
x

tensor([[0.2203, 0.1256],
        [0.9777, 0.6662]])

In [23]:
# addition
# x+2
# substraction
x - 2
# multiplication
x * 3
# division
x / 4
# int division
(x*100) // 3
# mod
((x*100) // 3)%2
# power
x ** 2

tensor([[0.0485, 0.0158],
        [0.9559, 0.4439]])

# 2.) Element Wise Operation

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9813, 0.9987, 0.7460],
        [0.1450, 0.2942, 0.6918]])
tensor([[0.4401, 0.2308, 0.6549],
        [0.0318, 0.7035, 0.1801]])


In [25]:
# addition
a + b
# substraction
a - b
# multiplication
a * b
# division
a / b
# mod
a % b


tensor([[0.1011, 0.0756, 0.0911],
        [0.0177, 0.2942, 0.1515]])

In [26]:
c = torch.tensor([1,-2,3,-4,5])

In [27]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [28]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4, -5])

In [29]:
d = torch.tensor([1.4, 2.3, 4.5, 6.7])

In [30]:
# round
torch.round(d)

tensor([1., 2., 4., 7.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 3., 5., 7.])

In [32]:
# floor
torch.floor(d)

tensor([1., 2., 4., 6.])

In [33]:
# clamp - all the value get into the range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3.) Reduction Operation

In [47]:
e = torch.randint(size = (2,3), low = 0, high = 10)
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [41]:
# sum
torch.sum(e)

# sum along column
torch.sum(e, dim = 0)

# sum along row
torch.sum(e, dim = 1)

tensor([13, 23])

In [50]:
# mean
torch.mean(f)

# mean along column
torch.mean(f, dim = 0)

tensor([5.0000, 7.5000, 3.0000])

In [ ]:
# median
torch.median(f)

# median along column
torch.median(f, )

tensor(5.)

In [53]:
# max and min
torch.max(f)

torch.min(f)

tensor(0.)

In [55]:
# standard deviation
torch.std(f)

tensor(2.7869)

In [57]:
# variance 
torch.var(f)

tensor(7.7667)

In [58]:
# argmax - tell the position of largest element
torch.argmax(e)

tensor(3)

In [59]:
torch.argmin(e)

tensor(1)

# 4.) Multiplication Operations 

In [66]:
g = torch.randint(size = (2,3), low = 0, high = 15)
h = torch.randint(size = (3,2), low = 0, high = 15)

print(f"g: {g}\n --------------------------------------")
print(f"h: {h}")


g: tensor([[ 9,  5,  6],
        [ 7, 12,  0]])
 --------------------------------------
h: tensor([[13, 13],
        [ 7,  5],
        [12,  1]])


In [67]:
# multiplication
torch.matmul(g,h)

tensor([[224, 148],
        [175, 151]])

In [68]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [ ]:
# dot product - a.b = [a1.b1+ a2.b2+ a3.b3]
torch.dot(vector1, vector2)

tensor(11)

In [71]:
# transpose
torch.transpose(g, 0, 1)

tensor([[ 9,  7],
        [ 5, 12],
        [ 6,  0]])

In [74]:
i = torch.randint(size = (3,3), low = 0, high = 15, dtype=torch.float32)
i

tensor([[13.,  1., 13.],
        [13.,  9.,  8.],
        [12.,  2.,  7.]])

In [75]:
# determinant - square matrix det(A) = ad - bc
torch.det(i)

tensor(-450.0000)

In [76]:
# inverse
torch.inverse(i)

tensor([[-0.1044, -0.0422,  0.2422],
        [-0.0111,  0.1444, -0.1444],
        [ 0.1822,  0.0311, -0.2311]])