In [2]:
import torch

In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("no")

no


# Creating a Tensor

In [4]:
# empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
# using zeroes 
# for initializing biases with 0 in NN
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand  0-1 value which will be random
torch.rand(2,3)

tensor([[0.0287, 0.8931, 0.5543],
        [0.0499, 0.3569, 0.4601]])

In [9]:
# # manual_seed
# torch.manual(100)
# torch.rand(2,3)

In [10]:
# tensor
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [11]:
# arange
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [12]:
# linspace -> linearly space
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

# Creating Matrix

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
# torch.rand_like(x)

# tensor Data type

In [18]:
x.dtype

torch.int64

In [19]:
torch.tensor([1.0,2.2,30.4], dtype = torch.int32)

tensor([ 1,  2, 30], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [21]:
#using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical operations

# 1. Scaler Operation

In [22]:
x = torch.rand(2,2)
x

tensor([[0.9171, 0.8492],
        [0.0805, 0.5979]])

In [23]:
# addition
# x+2
# substraction
x - 2
# multiplication
x * 3
# division
x / 4
# int division
(x*100) // 3
# mod
((x*100) // 3)%2
# power
x ** 2

tensor([[0.8412, 0.7212],
        [0.0065, 0.3575]])

# 2.) Element Wise Operation

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3037, 0.6618, 0.9154],
        [0.2305, 0.6062, 0.9464]])
tensor([[0.0742, 0.4505, 0.7573],
        [0.9926, 0.2946, 0.0435]])


In [25]:
# addition
a + b
# substraction
a - b
# multiplication
a * b
# division
a / b
# mod
a % b


tensor([[0.0068, 0.2113, 0.1580],
        [0.2305, 0.0170, 0.0326]])

In [26]:
c = torch.tensor([1,-2,3,-4,5])

In [27]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [28]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4, -5])

In [29]:
d = torch.tensor([1.4, 2.3, 4.5, 6.7])

In [30]:
# round
torch.round(d)

tensor([1., 2., 4., 7.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 3., 5., 7.])

In [32]:
# floor
torch.floor(d)

tensor([1., 2., 4., 6.])

In [33]:
# clamp - all the value get into the range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3.) Reduction Operation

In [34]:
e = torch.randint(size = (2,3), low = 0, high = 10)
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [35]:
# sum
torch.sum(e)

# sum along column
torch.sum(e, dim = 0)

# sum along row
torch.sum(e, dim = 1)

tensor([ 9, 12])

In [36]:
# mean
torch.mean(f)

# mean along column
torch.mean(f, dim = 0)

tensor([6.0000, 7.5000, 4.0000])

In [37]:
# median
torch.median(f)

# median along column
torch.median(f, )

tensor(6.)

In [38]:
# max and min
torch.max(f)

torch.min(f)

tensor(2.)

In [39]:
# standard deviation
torch.std(f)

tensor(2.1370)

In [40]:
# variance 
torch.var(f)

tensor(4.5667)

In [41]:
# argmax - tell the position of largest element
torch.argmax(e)

tensor(2)

In [42]:
torch.argmin(e)

tensor(5)

# 4.) Multiplication Operations 

In [43]:
g = torch.randint(size = (2,3), low = 0, high = 15)
h = torch.randint(size = (3,2), low = 0, high = 15)

print(f"g: {g}\n --------------------------------------")
print(f"h: {h}")


g: tensor([[ 2,  5, 14],
        [ 7,  3,  7]])
 --------------------------------------
h: tensor([[ 7, 11],
        [10,  6],
        [ 2,  0]])


In [44]:
# multiplication
torch.matmul(g,h)

tensor([[92, 52],
        [93, 95]])

In [45]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [46]:
# dot product - a.b = [a1.b1+ a2.b2+ a3.b3]
torch.dot(vector1, vector2)

tensor(11)

In [47]:
# transpose
torch.transpose(g, 0, 1)

tensor([[ 2,  7],
        [ 5,  3],
        [14,  7]])

In [48]:
i = torch.randint(size = (3,3), low = 0, high = 15, dtype=torch.float32)
i

tensor([[ 9.,  4.,  8.],
        [14.,  7., 10.],
        [ 5.,  1., 14.]])

In [49]:
# determinant - square matrix det(A) = ad - bc
torch.det(i)

tensor(40.0000)

In [50]:
# inverse
torch.inverse(i)

tensor([[ 2.2000, -1.2000, -0.4000],
        [-3.6500,  2.1500,  0.5500],
        [-0.5250,  0.2750,  0.1750]])

# 5.) Comparision Operator

In [51]:
j = torch.randint(size = (2,3), low = 0, high = 15)
k = torch.randint(size = (2,3), low = 0, high = 15)

print(j)
print(k)

tensor([[ 3,  7,  4],
        [ 8,  5, 10]])
tensor([[13, 12,  4],
        [10,  3, 10]])


In [52]:
# greater than
k > j

# less than
j < k

# not equal to 
j == k

tensor([[False, False,  True],
        [False, False,  True]])

## 6.) Special Function

In [53]:

l = torch.randint(size = (2,3), low = 0, high = 15, dtype = torch.float32)
l

tensor([[ 0., 10., 13.],
        [12.,  0.,  6.]])

In [54]:
# log
torch.log(l)

tensor([[  -inf, 2.3026, 2.5649],
        [2.4849,   -inf, 1.7918]])

In [55]:
# exp
torch.exp(l)

tensor([[1.0000e+00, 2.2026e+04, 4.4241e+05],
        [1.6275e+05, 1.0000e+00, 4.0343e+02]])

In [56]:
#sqrt
torch.sqrt(l)

tensor([[0.0000, 3.1623, 3.6056],
        [3.4641, 0.0000, 2.4495]])

In [57]:
# sigmoid 0-1
torch.sigmoid(l)

tensor([[0.5000, 1.0000, 1.0000],
        [1.0000, 0.5000, 0.9975]])

In [58]:
# softmax
torch.softmax(l, dim=0)

tensor([[6.1442e-06, 9.9995e-01, 9.9909e-01],
        [9.9999e-01, 4.5398e-05, 9.1105e-04]])

In [59]:
# relu
torch.relu(l)

tensor([[ 0., 10., 13.],
        [12.,  0.,  6.]])

#### for inplace operation after function we add _   eg- relu_()

# Clone

In [70]:
a = torch.randint(size = (2,3), low = 0, high = 15)
print(a)

tensor([[ 1, 12, 13],
        [ 1,  7,  9]])


In [71]:
b = a.clone()

In [72]:
a[0][0] = 10
print(a)

tensor([[10, 12, 13],
        [ 1,  7,  9]])


In [73]:
b

tensor([[ 1, 12, 13],
        [ 1,  7,  9]])

In [74]:
torch.cuda.is_available()

False

# Reshaping Tensor

In [75]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [77]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
b = torch.rand(size= (2,3,4))
b

tensor([[[0.0727, 0.3964, 0.8104, 0.1681],
         [0.7446, 0.5100, 0.3876, 0.7681],
         [0.1245, 0.5088, 0.6848, 0.1337]],

        [[0.8282, 0.4170, 0.6575, 0.3244],
         [0.9331, 0.4283, 0.6308, 0.2558],
         [0.0952, 0.4105, 0.4804, 0.1319]]])

In [81]:
# permute
b.permute(2,1,0).shape


torch.Size([4, 3, 2])

In [83]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [87]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and Tensor

In [88]:
import numpy as np

In [89]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [95]:
b = a.numpy()
b

array([1, 2, 3])

In [96]:
type(b)

numpy.ndarray

In [97]:
c = np.array([1,9,3])
c

array([1, 9, 3])

In [100]:
torch.from_numpy(c)

tensor([1, 9, 3])