In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("no")

no


# Creating a Tensor

In [3]:
# empty
a = torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
# using zeroes 
# for initializing biases with 0 in NN
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand  0-1 value which will be random
torch.rand(2,3)

tensor([[0.9913, 0.1631, 0.4898],
        [0.1095, 0.6897, 0.1072]])

In [8]:
# manual_seed
torch.manual(100)
torch.rand(2,3)

AttributeError: module 'torch' has no attribute 'manual'

In [ ]:
# tensor
torch.tensor([[1,2,3], [3,4,5]])

In [ ]:
# arange
torch.arange(1,10,2)

In [ ]:
# linspace -> linearly space
torch.linspace(0,10,10)

# Creating Matrix

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
x.shape

torch.Size([2, 3])

In [11]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# tensor Data type

In [14]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.0,2.2,30.4], dtype = torch.int32)

tensor([ 1,  2, 30], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
#using to 